easy_admin:
      
    site_name: 'Unnamed Site'
    design:
        menu:
            - { entity: 'User', label: 'Users', icon: 'user' }
            - { entity: 'Submission', label: 'Submissions', icon: 'envelope' }
            
            - { label: 'Documents' }
            - { entity: 'DocumentType', label: 'Document Types', icon: 'file' }
            - { entity: 'Card', label: 'Documents', icon: 'file-pdf' }
            
            - { label: 'Boards', icon: 'project-diagram' }
            - { entity: 'Board', label: 'Boards', icon: 'clipboard-check' }
            - { entity: 'Lists', label: 'Lists', icon: 'clipboard-list' }
            
    entities:
            
        User:
            class: App\Entity\User
            label: 'Users'
            list: 
                fields:
                    - { property: 'gravatar', type: 'image', label: 'Photo'}
                    - name 
                    - phone
                    - { property: 'email', type: 'email'}
                    - roles
            form: 
                fields:
                    - { type: 'group', columns: 6, label: 'Information', icon: 'user-circle', help: 'Your email address should be registered with gravatar.' }								
                    - firstName
                    - lastName
                    - phone
                    - { property: 'email', type: 'email'}
                    - country
                    - gender
                    - {type: 'group', columns: 6, label: 'Password', icon: 'lock'}
                    - {'property': 'password', type: 'repeated', type_options: {type: Symfony\Component\Form\Extension\Core\Type\PasswordType, required: true, first_options: {label: 'Password'}, second_options: {label: 'Confirm Password'} } }

        Board: 
           class: App\Entity\Board
           label: Boards
           list: 
              fields: 
                   - name
                   - description
                   - userId
                   - slug
              form: 
                  - name
                  - description
                  - userId
                  - slug
                  
        Lists: 
           class: App\Entity\Lists
           label: Lists
           
        Card: 
           class: App\Entity\Card
           label: Documents
        
        DocumentType: 
            class: App\Entity\DocumentType
            label: Document Types
           
        Submission: 
           class: App\Entity\Submission
           label: Submissions